services:
  # A Docker web service
  - type: web
    name: Emilia
    env: docker
    region: Singapore
    plan: free
    envVars:
      - key: PORT
        value: 80
      - key: BOT_TOKEN
        # value: BOT_TOKEN  
        sync: false
      - key: API_ID
        # value: API_ID
        sync: false
      - key: API_HASH
        # value: API_HASH
        sync: false
      - key: OWNER_ID
        # value: OWNER_ID
        sync: false
